steps:
  

# Step 2: Build and push web-server image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/web-server:latest', '-f', './modules/web-server/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/web-server:latest']
# Step 4: Deploy web-server to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - web-server
      - --image=us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/web-server:latest
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --add-cloudsql-instances=affiliate-center-447418:us-central1:affiliate-marketplace-db
      - --set-env-vars=POSTGRES_USER=postgres,POSTGRES_PASSWORD=6AAInxH\Irjq|7|v,POSTGRES_DB=postgres,DB_HOST=/cloudsql/affiliate-center-447418:us-central1:affiliate-marketplace-db,DB_PORT=5432,NODE_ENV=$_NODE_ENV,NETWORK_ENV=$_NETWORK_ENV,SERVER_PORT=8080,CLOUD_SQL_CONNECTION_NAME=${_PROJECT_ID}:us-central1:affiliate-marketplace-db

# Step 1: Build and push mini-app image
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        dir
        mkdir -p modules/mini-app/src/contracts
        cp -r build/AffiliateMarketplace/tact_AffiliateMarketplace.ts modules/mini-app/src/contracts/AffiliateMarketplace.ts
        cp -r build/Campaign/tact_Campaign.ts modules/mini-app/src/contracts/Campaign.ts

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/mini-app:latest'
      - '--build-arg'
      - 'NODE_ENV=${_NODE_ENV}'
      - '-f'
      - './modules/mini-app/Dockerfile'
      - '.'
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/web-server:latest', '--build-arg', 'NODE_ENV=${_NODE_ENV}','-f', './modules/web-server/Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/mini-app:latest']

  

  # Step 3: Deploy mini-app to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - mini-app
      - --image=us-central1-docker.pkg.dev/${_PROJECT_ID}/ton-affiliate-marketplace/mini-app:latest
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --update-env-vars=NODE_ENV=$_NODE_ENV,NETWORK_ENV=$_NETWORK_ENV,VITE_SERVER_PORT=8080,VITE_SERVER_NAME=tonAffiliate,SERVER_PORT=8080,BACKEND_URL=http://web-server.us-central1.run.app:8080

  

substitutions:
  _NODE_ENV: 'development'
  _NETWORK_ENV: 'testnet'
  _PROJECT_ID: 'affiliate-center-447418'
  
