version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    network_mode: host
    ports:
      - 443:433
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./modules/mini-app/dist:/var/www/tonaffiliates.com/html

  web-server:
    build:
      context: .
      dockerfile: ./modules/web-server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./modules/web-server/.env.${NODE_ENV}
      - ./modules/common/.env.${NETWORK_ENV}  # <-- Also load the "common" .env

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./modules/web-server/.env.${NODE_ENV}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
