services:
  web-server:
    build:
      context: .
      dockerfile: ./services/typescript-web-server/Dockerfile
    volumes:
      # Mount only the necessary source directories
      - ./services/typescript-web-server/src:/usr/src/app/src
      - ./services/common:/usr/src/app/src/common
      - ./wrappers:/usr/src/app/src/wrappers
      - ./build:/usr/src/app/src/build
      # Use an anonymous volume for node_modules to prevent overwriting
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./services/typescript-web-server/.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  mini-app:
    build:
      context: .
      dockerfile: ./services/affiliate-center-miniapp/Dockerfile
    env_file:
      - ./services/affiliate-center-miniapp/.env
    ports:
      - "5173:80"
    volumes:
      - ./services/affiliate-center-miniapp/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production

volumes:
  redis-data:
