services:
  web-server:
    build:
      context: .
      dockerfile: ./services/web-server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - ./services/web-server/.env.${NODE_ENV}
      - ./services/common/.env.${NETWORK_ENV}      # <-- Also load the "common" .env
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
